carts/urls.py
from django.urls import path


from . import views

app_name = 'carts'
urlpatterns = [    
    path('', views.cart, name='cart'),
]

facilito_store/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

from django.conf.urls.static import static
from django.conf import settings


from products.views import ProductsListView
from . import view

urlpatterns = [
    path( 'admin/', admin.site.urls ),
    path( '', ProductsListView.as_view(), name='index' ),
    path( 'user/logout', view.logout_view, name='logout' ),
    path( 'user/registro', view.registro_view, name='registro' ),
    path( 'user/login', view.login, name='login' ),
    
    path( 'products/', include( 'products.urls' ) ),
    path( 'carrito/', include( 'carts.urls' ) ),
    
]

if settings.DEBUG:
    urlpatterns += static( settings.MEDIA_URL, document_root=settings.MEDIA_ROOT )

products/urls.py
from django.urls import path

from .views import ProductDetailView, ProductSearchListView

app_name = 'products'

urlpatterns = [
    # path('<pk>', ProductDetailView.as_view(), name = 'product') # id -> llave primaria
    path( 'search', ProductSearchListView.as_view(), name='search' ),
    path('<slug:slug>', ProductDetailView.as_view(), name = 'product'), # id -> llave primaria
]

carts/models.py
from django.db import models

from users.models import User
from products.models import Product


class Cart(models.Model):
    user = models.ForeignKey( User, null=True, blank=True, on_delete=models.CASCADE  )
    Poductos =  models.ManyToManyField( Product )
    subtotal =  models.DecimalField( default=0.0, max_digits=8, decimal_places=2 )
    total =  models.DecimalField( default=0.0, max_digits=8, decimal_places=2 )
    create_at =  models.DateTimeField( auto_now_add=True )

    def __str__(self) -> str:
        return '1'

categorias/models.py
from django.db import models


from products.models import Product
## generar migracion de la tabla 
## python manage.py makemigrations
## agregar migraciones pendientes
## python manage.py migrate

class Categorias(models.Model):
    titulo = models.CharField( max_length=50 )
    detalles = models.TextField()
    create_at = models.DateTimeField(auto_now_add=True)

    # relacion de muchos a muchos
    products =  models.ManyToManyField( Product, blank=True )

    def __str__(self) -> str:
        return self.titulo

products/models.py
from django.db import models
from django.utils.text import slugify

import uuid

## generar migracion de la tabla 
## python manage.py makemigrations
## agregar migraciones pendientes
## python manage.py migrate

class Product(models.Model):
    titulo = models.CharField( max_length=50 )
    description = models.TextField()
    price = models.DecimalField( max_digits=8, decimal_places=2, default= 0.0 ) #123456.78
    slug =  models.SlugField( null=False, blank=False, unique=True )
    image = models.ImageField( upload_to='products/', null=False, blank=False )
    create_at = models.DateTimeField( auto_now_add=True )

    def __str__(self) -> str:
        return self.titulo

    def save( self, *args, **kwargs ):

        slug = slugify( self.titulo )        
        exist =Product.objects.filter(slug=slug).exists()

        if exist:
            self.slug = slugify( '{}-{}'.format( self.titulo, str( uuid.uuid4() )[:8] ) )
        else:
            self.slug = slug

        super( Product,self ).save( *args, **kwargs )

users/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser

## generar migracion de la tabla 
## python manage.py makemigrations
## agregar migraciones pendientes
## python manage.py migrate
class User(AbstractUser):
    
    def get_full_name( self ):
        return '{} {}'.format( self.first_name, self.last_name )
# Create your models here.

carts/views.py
from django.shortcuts import render

from .models import Cart

def cart( request ):
    user = request.user if request.user.is_authenticated else None
    cart_id = request.session.get('cart_id') 

    if cart_id is not None:
        cart = Cart.objects.get( pk=cart_id )
    else:
        cart = Cart.objects.create( user=user )

    request.session['cart_id'] = cart.id

    return render( request, 'carts/cart.html',{} )    

categorias/views.py
from django.shortcuts import render

# Create your views here.

products/views.py
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView

from django.db.models import Q

from products.models import Product



class ProductsListView(ListView):
    template_name = 'index.html'
    queryset = Product.objects.all().order_by('-id')

    def get_context_data( self, **kwargs ):
        contex =  super().get_context_data( **kwargs )
        contex['message'] = 'Listado de Productos'

        return contex


class ProductDetailView(DetailView):
    model = Product
    template_name = 'products/product.html'

    def get_context_data( self, **kwargs ):
        contex =  super().get_context_data( **kwargs )
        return contex


class ProductSearchListView(ListView):
    template_name = 'products/search.html'
    # queryset = 

    def get_queryset(self):        

        # titulo__icontains -> SELECT * FROM Products WHERE titulo LIKE '%%'
        filter1 = Q( titulo__icontains=self.query() )
        # categorias__titulo__icontains -> JOIN categoaria = productas WHERE categoaria.titulo LIKE '%%'
        filter2 = Q( categorias__titulo__icontains=self.query() )
        filters = filter1 | filter2

        return Product.objects.filter( filters )

    def query(self):
        return self.request.GET.get('q')
    
    def get_context_data( self, **kwargs ):
        contex =  super().get_context_data( **kwargs )
        contex['query'] = self.query()
        contex['count'] = contex['product_list'].count()

        return contex

users/views.py
from django.shortcuts import render

# Create your views here.

carts/templates/carts/cart.html
{% extends 'base.html' %}


{% block content %}
    <h2>Crito de compras</h2>
{% endblock content %}
    

products/templates/products/product.html
{% extends 'base.html' %}

{% block content %}
<dv class="col-3">
    {% if product.image is not  None %}
        <img src="{{ product.image.url }}" alt="imagel del producto" width="200", height="200">
    {% endif %}
</dv>

<div class="col">
    <h2>Detalles del productos</h2>

    <div class="h1">{{product.titulo}}</div>

    <div class="h5 font-weighr-bold">
        precios: <span class="text-danger">{{ product.price }}</span>
    </div>
    <div>
        <p> {{product.description}} </p>
    </div>


</div>
{% endblock %}

products/templates/products/search.html
{% extends 'base.html' %}

{% block content %}
<div class="col">
    <p>BUsqueda de productos</p>
    {% include 'products/snippets/search.html' with query=query %}
    <hr>
    <p>Resultados para: {{ query }}: ({{ count }})</p>
    
    <div class="row">
        {% for objet in product_list %}
        <div class="col-3 mt-5">
            <!-- Producto -->
            {% include 'products/snippets/product.html' with pruduct=objet %}
        </div>
        {% endfor %}
    </div>


    

</div>
{% endblock %}

products/templates/products/snippets/product.html
<div class="card" style="width: 18rem;">
    <img src="{{pruduct.image.url}}" class="card-img-top" alt="iagen" height="300" width="50">
    <div class="card-body">
        <h5 class="card-title">{{pruduct.titulo}}</h5>
        <p class="card-text">{{pruduct.description}}</p>
        <a href="{% url 'products:product' pruduct.slug %}" class="btn btn-primary">Ver mas</a>
    </div>
</div>

products/templates/products/snippets/search.html
<form action="{% url 'products:search' %}">
    <div class="input-group">
        <input type="text" name="q" value="{{ query }}" class="form-control" placeholder="Buscar">
        <div class="input-group-append">
            <input type="submit" name="" value="Buscar" class="btn btn-primary" >
        </div>
    </div>
</form>

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    

    <title>Document</title>
</head>
<body>
    {% include 'navbar.html' %}
    <div class="container">

       {% include 'message.html' %}


        <div class="row mt-5">

            {% block content %}
            {% endblock %}
            
        </div>
    </div>
</body>

<script src="https://kit.fontawesome.com/9aa9a0d9a0.js" crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>

</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="col">
    <h4 class="text-center"> {{ message }} </h4>

    {% include 'products/snippets/search.html' %}

    <div class="row">
        {% for objet in product_list %}
        <div class="col-3 mt-5">
            <!-- Producto -->
            {% include 'products/snippets/product.html' with pruduct=objet %}
        </div>
        {% endfor %}
    </div>

</div>
{% endblock %}

templates/message.html
{% if messages is not None %}
{% for message in messages %}

    <!-- {% if message.tags == 'success' %}
        <div class="alert alert-success"> {{ message }} </div>
    {% else %}
        <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert">x</button>
            {{ message }}
        </div>
    {% endif %} -->

    <div role="alert"class="alert alert-dismissible {% if message.tags == 'success' %}alert-success{% else %}alert-danger{% endif %}">
        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        {{ message }}
    </div>

{% endfor %}
{% endif %}

templates/navbar.html
{% url 'login' as login %}
{% url 'registro' as registro %}
{% url 'logout' as logout %}
{% url 'carts:cart' as cart %}

<nav class="navbar navbar-expand-md bg-dark navbar-dark">


  <div class="container-fluid">
    <a href="{% url 'index' %}" class="navbar-brand">Facilito store</a>


    <div class="d-flex">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
        data-bs-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="true"
        aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>


      <div class="collapse navbar-collapse " id="navbarToggleExternalContent">

        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link {% if cart == request.path %}active{% endif %}" href="{{ cart }}">
              My Carrito <i class="fas fa-shopping-cart"></i>
            </a>
          </li>
          <li class="nav-item"><a href=""></a></li>
        </ul>


        <ul class="navbar-nav">

          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{{ logout }}"> <span class="fas fa-sign-in-alt"></span>
              Logout </a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link {% if request.path == login %}active{% endif %}" href="{{ login }}">
              <span class="fas fa-user"></span>
              Login
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if request.path == registro %}active{% endif %}" href="{{ registro }}">
              <i class="fas fa-user-plus"></i>
              Registro
            </a>
          </li>
          {% endif %}


        </ul>
      </div>

    </div>
  </div>




</nav>

templates/user/login.html
{% extends 'base.html' %}

{% block content %}
<div class="col">
    <h2>Login</h2>

    <form method="post">
        {% csrf_token %}

        <div class="fomr-group">
            <label for="username">Usuario</label>
            <input type="text" name="username" class="form-control">
        </div>
        <div class="fomr-group">
            <label for="paswword">COntraseña</label>
            <input type="password" name="paswword" class="form-control">
        </div>

        <button type="submit" class="btn btn-primary">Login</button>

    </form>

</div>
{% endblock %}

templates/user/registro.html
{% extends 'base.html' %}
{% block content %}
<div class="col">
    <h2>Registro</h2>

    <form method="post">
        {% csrf_token %}

        <!-- <div class="fomr-group">
            {{ form.userName.label_tag }}
            {{ form.userName }}
            
            {% if form.userName.errors is not None %}
                {{ form.userName.errors }}
            {% endif %}
            
        </div>
        <div class="fomr-group">
            {{ form.email.label_tag }}
            {{ form.email }}
            
            {% if form.email.errors is not None %}
                {{ form.email.errors }}
            {% endif %}
            
        </div>
        <div class="fomr-group">
            {{ form.passw.label_tag }}
            {{ form.passw }}
            
            {% if form.passw.errors is not None %}
                {{ form.passw.errors }}
            {% endif %}
            
        </div> -->

        {% for fiel in form %}
        <div class="fomr-group">
            {{ fiel.label_tag }}
            {{ fiel }}

            {% if fiel.errors is not None %}
            {{ fiel.errors }}
            {% endif %}

        </div>
        {% endfor %}


        <button type="submit" class="btn btn-primary">Registrar</button>
    </form>

</div>
{% endblock %}